// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	account "megitron/apps/backend/internal/handler/account"
	delegate "megitron/apps/backend/internal/handler/delegate"
	exchange "megitron/apps/backend/internal/handler/exchange"
	user "megitron/apps/backend/internal/handler/user"
	"megitron/apps/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tron/account",
				Handler: account.TronAccountGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tron/account/create",
				Handler: account.TronAccountCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/delegate/order/list",
				Handler: delegate.DelegateOrderListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/exchange/order/list",
				Handler: exchange.ExchangeOrderListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/create",
				Handler: user.UserCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
