// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DelegateOrderListReq struct {
}

type DelegateOrderListResp struct {
}

type ExchangeOrderCreateReq struct {
	Typo     string  `json:"typo"`
	Amount   float64 `json:"amount"`
	Telegram string  `json:"telegram"`
	WhatsApp string  `json:"whatsapp"`
	WeChat   string  `json:"wechat"`
	Other    string  `json:"other"`
}

type ExchangeOrderCreateResp struct {
	Id  uint64 `json:"id"`
	Msg string `json:"msg"`
}

type ExchangeOrderListReq struct {
}

type ExchangeOrderListResp struct {
}

type Paged struct {
	Page  int64 `json:"page"`
	Limit int64 `json:"limit"`
	Total int64 `json:"total"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type ResourceDelegateReq struct {
	Type     int8   `json:"type"`
	Owner    string `json:"owner"`
	Receiver string `json:"receiver"`
}

type ResourceDelegateResp struct {
	TransactionId string `json:"transaction_id"`
}

type Response struct {
	Msg string `json:"msg"`
}

type TransferListReq struct {
	Address string `json:"address"`
}

type TransferListResp struct {
}

type TransferTrxCreateReq struct {
	Amount int64  `json:"amount"`
	From   string `json:"from"`
	To     string `json:"to"`
}

type TransferTrxCreateResp struct {
	TransactionId string `json:"transaction_id"`
	Msg           string `json:"msg"`
}

type TransferUsdtCreateReq struct {
	Amount int64  `json:"amount"`
	From   string `json:"from"`
	To     string `json:"to"`
}

type TransferUsdtCreateResp struct {
	TransactionId string `json:"transaction_id"`
	Msg           string `json:"msg"`
}

type TronAccountCreateReq struct {
}

type TronAccountCreateResp struct {
}

type TronAccountGetReq struct {
}

type TronAccountGetResp struct {
}

type UserCreateReq struct {
}

type UserCreateResp struct {
}
