// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Contacts struct {
	Telegram string `json:"telegram"`
	WhatsApp string `json:"whatsapp"`
	Wechat   string `json:"wechat"`
	Other    string `json:"other"`
}

type DelegateBillGetReq struct {
	OrderId int64 `json:"order_id"`
}

type DelegateBillGetResp struct {
	Bill DelegateBillItem
}

type DelegateBillItem struct {
	Id              int64  `json:"id"`
	OrderId         int64  `json:"order_id"`
	TransactionId   string `json:"transaction_id"`
	Status          int16  `json:"status"`
	From            string `json:"from"`
	To              string `json:"to"`
	DelegatedAmount int64  `json:"delegated_amount"`
	Contacts
	CreatedAt int64 `json:"created_at"`
}

type DelegateOrderItem struct {
	Id             int64   `json:"id"`
	TransactionId  string  `json:"transaction_id"`
	Status         string  `json:"status"`
	Currency       string  `json:"currency"`
	ReceivedAmount float64 `json:"received_amount"`
	ReceivedSun    int64   `json:"received_sun"`
	FromBase58     string  `json:"from_base58"`
	ToBase58       string  `json:"to_base58"`
	WithdrawTime   int64   `json:"withdraw_time"`
	Description    string  `json:"description"`
	Contacts
	CreatedAt int64 `json:"created_at"`
}

type DelegateOrderListReq struct {
	Pages
	TransactionId string `json:"transaction_id"`
	Status        string `json:"status"`
	FromBase58    string `json:"from_base58"`
	ToBase58      string `json:"to_base58"`
	Typo          string `json:"typo"`
	Start         int64  `json:"start"`
	End           int64  `json:"end"`
}

type DelegateOrderListResp struct {
	Items []*DelegateOrderItem `json:"items"`
	Total int64                `json:"total"`
}

type DelegateWithdrawGetReq struct {
	OrderId int64
}

type DelegateWithdrawGetResp struct {
	Withdraw DelegateWithdrawItem
}

type DelegateWithdrawItem struct {
	Id                int64  `json:"id"`
	OrderId           int64  `json:"order_id"`
	TransactionId     string `json:"transaction_id"`
	Typo              string `json:"typo"`
	From              string `json:"from"`
	To                string `json:"to"`
	UnDelegatedAmount int64  `json:"un_delegated_amount"`
	Description       string `json:"description"`
	CreatedAt         int64  `json:"created_at"`
}

type ExchangeOrderCreateReq struct {
	Typo     string  `json:"typo"`
	Amount   float64 `json:"amount"`
	Telegram string  `json:"telegram"`
	WhatsApp string  `json:"whatsapp"`
	WeChat   string  `json:"wechat"`
	Other    string  `json:"other"`
}

type ExchangeOrderCreateResp struct {
	Id  uint64 `json:"id"`
	Msg string `json:"msg"`
}

type ExchangeOrderListReq struct {
}

type ExchangeOrderListResp struct {
}

type Pages struct {
	Page  int `json:"page"`
	Limit int `json:"limit"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Msg string `json:"msg"`
}

type TronAccountCreateReq struct {
}

type TronAccountCreateResp struct {
}

type TronAccountGetReq struct {
}

type TronAccountGetResp struct {
}

type UserCreateReq struct {
}

type UserCreateResp struct {
}
